org: mrlibr
app: be-nodejs-aws
service: product-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: 'webpack.config.js'   # Name of webpack configuration file
    includeModules: true   # Node modules configuration for packaging
    packager: 'npm'   # Packager that will be used to package your external modules
    excludeFiles: src/**/*.test.js # Provide a glob for files to ignore
  serverless-offline:
    httpPort: 3900

package:
  individually: true
  patterns:
    - "!*"
    - "!*/**"
    - dist/**

functions:
  getAllProduct:
    handler: dist/index.handler
    events:
      - http: 'GET /products'
  getProductById:
    handler: dist/index.handler
    events:
      - http: 'GET /products/{proxy+}'
  addNewProduct:
    handler: dist/index.handler
    events:
      - http: 'POST /add-product'
