org: mrlibr
app: be-nodejs-aws
service: import-service
frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  stage: dev
  runtime: nodejs14.x
  environment:
    CATALOG_ITEMS_QUEUE:
      Ref: ItemsQueue

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline

iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::${env:AWS_IMPORT_BUCKET}"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::${env:AWS_IMPORT_BUCKET}/*"
    - Effect: 'Allow'
      Action: 'sqs:*'
      Resource:
        - Fn::GetAtt: [ CATALOG_ITEMS_QUEUE, Arn ]

custom:
  webpack:
    webpackConfig: 'webpack.config.js'   # Name of webpack configuration file
    includeModules: true   # Node modules configuration for packaging
    packager: 'npm'   # Packager that will be used to package your external modules
    excludeFiles: src/**/*.test.js # Provide a glob for files to ignore
  serverless-offline:
    httpPort: 3900

resources:
  Resources:
    ItemsQueue:
        Type: 'AWS::SQS::Queue'
        Properties:
          QueueName: '${env:SQS_QUEUE_NAME}'

package:
  individually: true
  patterns:
    - "!*"
    - "!*/**"
    - dist/**

functions:
  importProductsFile:
    handler: dist/index.handler
    events:
      - http:
          method: GET
          path: '/import'
        request:
            parameters:
              querystrings:
                name: true
  importFileParser:
    handler: dist/handlers/index.importFileParser
    events:
      - s3:
          bucket: ${env:AWS_IMPORT_BUCKET}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
            - suffix: .csv
          existing: true
    GatewayResponseDefault4xx:
      Type: AWS::ApiGateway::GatewayResponse
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
          gatewayresponse.header.Access-Control-Allow-Methods: "'GET,OPTIONS'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: ApiGatewayRestApi
